#!/usr/bin/env bash

# Author : Daiki Maekawa

echo ""
echo "Bring up the usb modules connection"
echo ""

cp `rospack find icart_mini_setup`/config/70-sensors.rules /etc/udev/rules.d

echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart
